services:
  - type: web
    name: credlocity-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://credlocity:Credlocity2024@cluster0.mongodb.net/?retryWrites=true&w=majority
      - key: DB_NAME
        value: credlocity
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.7

  - type: web
    name: credlocity-website
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install --legacy-peer-deps && REACT_APP_BACKEND_URL=https://credlocity-api.onrender.com npx craco build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
