services:
  - type: web
    name: credlocity-api
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install fastapi uvicorn motor pymongo pydantic python-jose passlib bcrypt python-dotenv python-multipart pillow reportlab stripe starlette cryptography httpx Jinja2
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://claw-setup-4bx5n:d6pevp4lqs2c73eepqh0@customer-apps.vur8w0.mongodb.net/?retryWrites=true&w=majority
      - key: DB_NAME
        value: claw-setup-4bx5n-test_database
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

  - type: web
    name: credlocity-website
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install --legacy-peer-deps && REACT_APP_BACKEND_URL=https://credlocity-api.onrender.com npx craco build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
